### ISSUE TITLE
Ionic code hints not working

### ISSUE THREAD

**Issue by nileshlg2003** [chrisgriffith/IonicBrackets#4]
Hi,

I am using Bracket 1.2, and I have installed this extension successfully (It shows as installed in extension manager) but when am typing ion-tags I can't see any ionic code hints. Am i doing something wrong?

**Comment by chrisgriffith** [comment]
The only known issue that there can only be on Code Hinting engine enabled. Check that you don't have another Code Hinter installed.

**Comment by nileshlg2003** [comment]
Thanks, it worked. I had two extensions for AngularJS Material Design and IonicBrackets, Removed AngularJS hints and its working now.

**Comment by chrisgriffith** [comment]
Great. Need to look further into this (especially since I have written 3 and another in development.)
