### ISSUE TITLE
not working in my brackets 

### ISSUE THREAD

**Issue by rishabh1403** [chrisgriffith/IonicBrackets#7]
did install this extension last night , but it doesn't work even after restarting the editor

**Comment by chrisgriffith** [comment]
My first guess is you might have another code hinter installed.
Unfortunately, Brackets only allows one at a time.

Uninstall the other hinter and see if that resolves the issue.

If that does not work, please send me a list of the extensions you have
installed and I will see what might be up.

Thanks,

Chris

**Comment by rishabh1403** [comment]
Yeah i had AngularJs Hinter installed , removing that solved the issue . Thanks For your help , one quick question , what if i want two code hinter to work ? like if i am working with ionic i would need angular too . Any solution for that ?

Thanks ,
Rishabh

**Comment by chrisgriffith** [comment]
There are some Angular hints that are in the Ionic hinter, so you should be
ok. If you find a tag that is not supported let know and I can add it in.

Chris

**Comment by rishabh1403** [comment]
Thank you for all your help :+1:  I think its time we close the issue :)

**Comment by GouravS** [comment]
Hi,

As I can see above, this does not work with other angular extension, can you please suggest an extension which provides support for both angular and ionic as in the current situation with an angular extension in place not able to use your ionic one. Or would be great if this can be fixed to work with other angular or any other extension.

Thanks,
Gourav

**Comment by chrisgriffith** [comment]
This issue lies with the base engine. There are angular directives built
into the Ionic hinter to attempt to deal with the conflict. What elements
aren't you able to use?

Which angular extension are you using?

**Comment by GouravS** [comment]
Hi,

It doesn't show any of the ion-\* elements to use. I'm using "AngularJS Code hints" extension.

Thanks,
Gourav

**Comment by rishabh1403** [comment]
Hi ,
I used this Ionic-Brackets-Extension and disabled all other angularjs code hinter , and i was able to get ionic and angular code hints . You may try this .
Thanks.

**Comment by GouravS** [comment]
Hi,

Do you mean "ionic-brackets" by Oz sayag? 
Thanks.

**Comment by GouravS** [comment]
Hi,

Alright, you are referring to the one by Chris. And yes, it works for both Angular & ionic if I disable all others. But I was also using "ionic-brackets" by Oz sayag as that provides easy way to add platform, plugin plus more. Would be great if we can find a way to get past the restriction of using only 1. 

Thanks,
Gourav

**Comment by rishabh1403** [comment]
Hi ,
Yeah that would have been great , but that is the problem with brackets , but for now i use the one by Chris 
Thanks
